### ISSUE TITLE
Comparable AIC, R2 for ALCC and NLS models

### ISSUE THREAD

**Issue by austinwpearce** [adriancorrendo/soiltestcorr#10]
AIC (tidy output) and r (Pearson's correlation in plot) are both based on the linear, transformed data. As such, they are not really comparable to the AIC/R<sup>2</sup> of the Mitscherlich, LP, or QP models.

I am working on adapting some contributed code to work with the updated `mod_alcc()`.

For comparison, I tested the ALCC and two NLS models on dataset. The results were:
| Model                                        | AIC  | r    | R<sup>2</sup>  |
|----------------------------------------------|------|------|------|
| ALCC with smatr on transformed scale         | 19.7 | 0.76 |      |
| ALCC on original scale with contributed code | 299  |      | 0.81 |
| Mitscherlich                                 | 283  |      | 0.87 |
| QP                                           |  280 |      | 0.88 |

**Comment by adriancorrendo** [comment]
Interesting!

I'm wondering how to get the AIC of ALCC expressed on the original scale?
It makes sense that the alcc is worse than least squares since the LS models are set to minimize a loss function in terms of Y, while the alcc does it in both X and Y directions.

That's why I would be a bit concerned, because the AIC of the SMA (which is not comparable) considers the likelihood (i.e. a bivariate distribution) while the AIC on original scale I guess does not.

**Comment by adriancorrendo** [comment]
I proceed to close this issue that has been addressed a while ago. The latest version of the code ([mod_alcc.R](https://github.com/adriancorrendo/soiltestcorr/blob/main/R/mod_alcc.R)) includes goodness of fit for both "sma" and "alcc" (e.g. AIC_sma, AIC_alcc).

Adrian

**Comment by austinwpearce** [comment]
Good call!
